server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wage  # 数据库连接URL
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
